[project]
name = "ansible-modules-dx"
version = "0.0.1"
requires-python = ">=3.10, <3.13"
dependencies = ["ansible==10.7.0"]

[dependency-groups]
dev = ["ruff>=0.14.10"]

[tool.uv]
managed = true
package = false
